package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"saitama/gql/graph/generated"
	modelsGen "saitama/gql/graph/models_gen"
	db "saitama/infrastructure/sqlite"
	"saitama/modules/users/repository"
	"saitama/modules/users/usecase"
)

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id int64) (*modelsGen.User, error) {
	uc := usecase.NewUserUsecase(db.GetDatabaseConnection(), repository.NewUserRepository(db.GetDatabaseConnection()))
	userData, err := uc.GetUser(ctx, uint64(id))
	if err != nil {
		return nil, err
	}

	return &modelsGen.User{
		ID:        int64(userData.ID),
		Name:      userData.Name,
		Email:     userData.Email,
		CreatedAt: userData.CreatedAt,
		UpdatedAt: userData.UpdatedAt,
	}, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
