package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"saitama/gql/graph/generated"
	modelsGen "saitama/gql/graph/models_gen"
	db "saitama/infrastructure/sqlite"
	"saitama/internal/common/models"
	"saitama/modules/users/repository"
	"saitama/modules/users/usecase"
)

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id int64) (*modelsGen.ResponseUser, error) {
	uc := usecase.NewUserUsecase(db.GetDatabaseConnection(), repository.NewUserRepository(db.GetDatabaseConnection()))
	userData, err := uc.GetUser(ctx, uint64(id))
	if err != nil {
		return nil, err
	}

	response := &modelsGen.ResponseUser{
		Items: &modelsGen.User{
			ID:        int64(userData.ID),
			Name:      userData.Name,
			Email:     userData.Email,
			CreatedAt: userData.CreatedAt,
			UpdatedAt: userData.UpdatedAt,
		},
	}

	return response, nil
}

// GetUserList is the resolver for the getUserList field.
func (r *queryResolver) GetUserList(ctx context.Context, option *models.QueryOption) (*modelsGen.ResponseUserList, error) {
	uc := usecase.NewUserUsecase(db.GetDatabaseConnection(), repository.NewUserRepository(db.GetDatabaseConnection()))
	users, err := uc.GetUserList(ctx, option)
	if err != nil {
		return nil, err
	}
	return &modelsGen.ResponseUserList{
		Items: func() []*modelsGen.User {
			var userList []*modelsGen.User
			for _, user := range users {
				userList = append(userList, &modelsGen.User{
					ID:        int64(user.ID),
					Name:      user.Name,
					Email:     user.Email,
					CreatedAt: user.CreatedAt,
					UpdatedAt: user.UpdatedAt,
				})
			}
			return userList
		}(),
	}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
