// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package modelsGen

import (
	"saitama/internal/common/models"
	"time"
)

type Query struct {
}

type ResponseUser struct {
	Items *User `json:"items"`
}

type ResponseUserList struct {
	Items      []*User            `json:"items"`
	Pagination *models.Pagination `json:"pagination"`
}

type Role struct {
	ID        int64      `json:"id"`
	RoleName  string     `json:"role_name"`
	RoleType  int64      `json:"role_type"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

type User struct {
	ID        int64      `json:"id"`
	Name      string     `json:"name"`
	Email     string     `json:"email"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

type UserRole struct {
	ID        int64      `json:"id"`
	UserID    int64      `json:"user_id"`
	RoleID    int64      `json:"role_id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}
