// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package modelsGen

import (
	"time"
)

type Query struct {
}

type ResponseUsers struct {
	Items *User `json:"items"`
}

type ResponseUsersList struct {
	Items []*User `json:"items"`
}

type Role struct {
	ID        string     `json:"id"`
	RoleName  string     `json:"role_name"`
	RoleType  string     `json:"role_type"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

type User struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}

type UserRole struct {
	ID        string     `json:"id"`
	UserID    string     `json:"user_id"`
	RoleID    string     `json:"role_id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}
